### ISSUE TITLE
EvaluateScriptAsync exception

### ISSUE THREAD

**Issue by sshepelevich** [cefsharp/CefSharp#1366]
Hi guys,

As a part of our application flow, we transfer large amount of data back and forth between C# & Chromium.

However, when I execute EvaluateScriptAsync() and expect to receive(from chromium) 23Mb large, string, AggregateException is being raised on Task.Wait().

2015-10-23 11:50:26,869 [9] ERROR [(null)] - Method: 'Void CurrentDomain_UnhandledException(Object, UnhandledExceptionEventArgs)'. Line: ~115. System.AggregateException: One or more errors occurred. ---> System.ServiceModel.CommunicationException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.

Server stack trace: 
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.EndEvaluateScriptAsync(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

Are there any real data size limitations for the data exchange operations? Or any ideas what can cause the exception? It happens on CefSharp v39 and various OS such as Windows 7, 8.1, so the problem is OS version independent.

Thanks in advance.

**Comment by amaitland** [comment]
> Are there any real data size limitations for the data exchange operations?

The `WCF` service used has quite a few limitations. The max should be `128mb`, though some other tweaks may be required.

https://github.com/cefsharp/CefSharp/blob/cefsharp/39/CefSharp/Internals/BrowserProcessServiceHost.cs#L124

The latest stable version `43.0.0` doesn't use `WCF` for `EvaluateScriptAsync`, it uses the native `IPC` provided by `CEF`, the limit for it is `128mb`, it may be a little more forgiving when transferring large amounts of data.

**Comment by sshepelevich** [comment]
Thank you very much! 

It is quite odd though. Nuget shows that I'm using cefsharp 39. But when I decompile BrowserProcessServiceHost, there is SixteenMegaBytesInBytes constant instead of OneHundredAndTwentyEightMegaBytesInBytes.

Assembly's location is \packages\CefSharp.Common.39.0.0\CefSharp\x86\CefSharp.dll, so I'm confident that  I'm using 39th version. 

Anyway, thanks again! From here I know where to dig in.

**Comment by amaitland** [comment]
`39.0.2` is the newest `39` release, looks like it was increased in the `39.0.1` release.
