### ISSUE TITLE
Visual Studio 2015 CefSharp Pre-release

### ISSUE THREAD

**Issue by Justin-Lopez** [cefsharp/CefSharp#1419]
I'm currently trying to install the pre-release of CefSharp since that's the only version that supports it from my knowledge. I keep getting this error: http://prntscr.com/93aur7

Output of Package Manager:

```
Attempting to gather dependencies information for package 'CefSharp.WinForms.45.0.0-pre01' with respect to project 'StarQ Media', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'CefSharp.WinForms.45.0.0-pre01' with DependencyBehavior 'Lowest'
Resolving actions to install package 'CefSharp.WinForms.45.0.0-pre01'
Resolved actions to install package 'CefSharp.WinForms.45.0.0-pre01'
For adding package 'cef.redist.x64.3.2454.1344' to project 'StarQ Media' that targets 'net45'.
For adding package 'cef.redist.x64.3.2454.1344' to project 'StarQ Media' that targets 'net45'.
Adding package 'cef.redist.x64.3.2454.1344' to folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages'
Added package 'cef.redist.x64.3.2454.1344' to folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages'
Added package 'cef.redist.x64.3.2454.1344' to 'packages.config'
Added file 'packages.config' to project 'StarQ Media'.
Successfully installed 'cef.redist.x64 3.2454.1344' to StarQ Media
Install failed. Rolling back...
Package 'cef.redist.x86 3.2454.1344' does not exist in project 'StarQ Media'
Removed file 'packages.config' from folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\StarQ Media'.
Removed package 'cef.redist.x64 3.2454.1344' from 'packages.config'
Removed file 'packages.config'
Package 'cef.redist.x86 3.2454.1344' does not exist in folder 'C:\Users\Jusin\documents\visual studio 2015\Projects\StarQ Media\packages'
Removing package 'cef.redist.x64 3.2454.1344' from folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages'
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344\CEF\locales'.
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344\CEF\x64'.
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344\build'.
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344\CEF'.
Removed file 'cef.redist.x64.3.2454.1344.nupkg' from folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344'.
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages\cef.redist.x64.3.2454.1344'.
Removed folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages'.
Removed package 'cef.redist.x64 3.2454.1344' from folder 'C:\Users\Justin\documents\visual studio 2015\Projects\StarQ Media\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
```

**Comment by amaitland** [comment]
> I'm currently trying to install the pre-release of CefSharp since that's the only version that supports it from my knowledge.

Compiling from source is supported under `VS2015` in the `2454` branch and newer. Just using the packages you can use older version, just need to make sure the relevant `VC++ Redist` version is installed.

Do you have the latest `Nuget` installed?

If I create an empty `WinForms` project and install the `Nuget` packages everything works fine.

```
Attempting to gather dependencies information for package 'CefSharp.WinForms.45.0.0-pre01' with respect to project 'WindowsFormsApplication1', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'CefSharp.WinForms.45.0.0-pre01' with DependencyBehavior 'Lowest'
Resolving actions to install package 'CefSharp.WinForms.45.0.0-pre01'
Resolved actions to install package 'CefSharp.WinForms.45.0.0-pre01'
For adding package 'cef.redist.x64.3.2454.1344' to project 'WindowsFormsApplication1' that targets 'net46'.
For adding package 'cef.redist.x64.3.2454.1344' to project 'WindowsFormsApplication1' that targets 'net46'.
Adding package 'cef.redist.x64.3.2454.1344' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'cef.redist.x64.3.2454.1344' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'cef.redist.x64.3.2454.1344' to 'packages.config'
Added file 'packages.config' to project 'WindowsFormsApplication1'.
Successfully installed 'cef.redist.x64 3.2454.1344' to WindowsFormsApplication1
For adding package 'cef.redist.x86.3.2454.1344' to project 'WindowsFormsApplication1' that targets 'net46'.
For adding package 'cef.redist.x86.3.2454.1344' to project 'WindowsFormsApplication1' that targets 'net46'.
Adding package 'cef.redist.x86.3.2454.1344' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'cef.redist.x86.3.2454.1344' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'cef.redist.x86.3.2454.1344' to 'packages.config'
Successfully installed 'cef.redist.x86 3.2454.1344' to WindowsFormsApplication1
For adding package 'CefSharp.Common.45.0.0-pre01' to project 'WindowsFormsApplication1' that targets 'net46'.
For adding package 'CefSharp.Common.45.0.0-pre01' to project 'WindowsFormsApplication1' that targets 'net46'.
Adding package 'CefSharp.Common.45.0.0-pre01' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'CefSharp.Common.45.0.0-pre01' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'CefSharp.Common.45.0.0-pre01' to 'packages.config'
Successfully installed 'CefSharp.Common 45.0.0-pre01' to WindowsFormsApplication1
For adding package 'CefSharp.WinForms.45.0.0-pre01' to project 'WindowsFormsApplication1' that targets 'net46'.
For adding package 'CefSharp.WinForms.45.0.0-pre01' to project 'WindowsFormsApplication1' that targets 'net46'.
Adding package 'CefSharp.WinForms.45.0.0-pre01' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'CefSharp.WinForms.45.0.0-pre01' to folder 'c:\users\alex\documents\visual studio 2015\Projects\WindowsFormsApplication1\packages'
Added package 'CefSharp.WinForms.45.0.0-pre01' to 'packages.config'
Successfully installed 'CefSharp.WinForms 45.0.0-pre01' to WindowsFormsApplication1
========== Finished ==========
```

**Comment by Justin-Lopez** [comment]
I have the latest `Nuget` installed but I'ma see if its `VS C++ Redist` messing this up..

**Comment by amaitland** [comment]
See below for the `VC++` requirements per branch.
https://github.com/cefsharp/CefSharp#version-branches

> System.NullReferenceException: Object reference not set to an instance of an object. at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()

Are you sure your using the latest version? It may be a `Nuget` problem your experiencing.

https://github.com/NuGet/Home/issues/1367

**Comment by Justin-Lopez** [comment]
It's still not working.. I have  the latest `VC++` installed and the latest `Nuget` installed. I checked for updates and nothing came up.

**Comment by amaitland** [comment]
Tested successfully with `3.1.1.0` and `3.2.0.10516`

https://github.com/NuGet/Home/issues/1367#issuecomment-152529404

**Comment by Justin-Lopez** [comment]
I have version `3.2.0.10516` installed.. Not sure why its not working..

**Comment by amaitland** [comment]
Can you try updating to `3.2.1-rc` as suggested here https://github.com/NuGet/Home/issues/1367#issuecomment-152573787

You can find `3.2.1-rc` on https://dist.nuget.org/index.html

**Comment by Justin-Lopez** [comment]
Thank you, updating to `3.2.1-rc` solved the issue.
