### ISSUE TITLE
WPF crashing with open combobox

### ISSUE THREAD

**Issue by goeranbarz** [cefsharp/CefSharp#1723]
- **What version of the product are you using?**
  49.0.1 from NuGet
- **What architecture x86 or x64?**
   x64
- **On what operating system?**
  Windows 8.1
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF
- **What steps will reproduce the problem?**
  Here is a simple html code which will cause the problem in the MinimalExample.WPF. The MinimalExample.Winforms seems to work correctly:

`<html>
    <body>
        <p>
            <select>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                </select>
        </p>
    </body>
</html>`
- Open the combobox on the html page
- Move the mouse out of the browser to the windows task bar while the combobox is still open (Moving it to another window also often causes this error)
- Move the mouse back to the open combobox
- The program crashes with an exception: 
  "An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in WindowsBase.dll"
- **What is the expected output? What do you see instead?**
  Leaving the current window while a combobox is still open shouldn't cause any problems
- **Please provide any additional information below.**
  - debug.log is empty
- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
  No

**Comment by amaitland** [comment]
> "An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in WindowsBase.dll"

Can you provide a symbolized stack trace please. Instructions for downloading `libcef.dll.pdb` are in the troubleshooting wiki article.

> Does this problem also occur in the Cef TestApp from http://cefbuilds.com?
> No

Have you tested this?

**Comment by amaitland** [comment]
Looks like it's purely a `WPF` exception.

```c#
System.ComponentModel.Win32Exception was unhandled
  _HResult=-2147467259
  _message=The operation completed successfully
  HResult=-2147467259
  IsTransient=false
  Message=The operation completed successfully
  Source=WindowsBase
  ErrorCode=-2147467259
  NativeErrorCode=0
  StackTrace:
       at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
       at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
       at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
       at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
       at System.Windows.Controls.Primitives.Popup.PopupSecurityHelper.BuildWindow(Int32 x, Int32 y, Visual placementTarget, Boolean transparent, HwndSourceHook hook, AutoResizedEventHandler handler)
       at System.Windows.Controls.Primitives.Popup.BuildWindow(Visual targetVisual)
       at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
       at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
       at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
       at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
       at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
       at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
       at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
       at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
       at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
       at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
       at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
       at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
       at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
       at MS.Internal.Data.ClrBindingWorker.OnSourceInvalidation(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
       at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
       at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
       at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
       at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
       at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
       at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
       at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
       at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
       at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent()
       at System.Windows.Controls.PopupControlService.InspectElementForToolTip(DependencyObject o)
       at System.Windows.Controls.PopupControlService.OnMouseMove(IInputElement directlyOver, Point pt)
       at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
       at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.MouseDevice.Synchronize()
       at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
       at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode)
       at System.Windows.Input.Mouse.Capture(IInputElement element)
       at CefSharp.Wpf.ChromiumWebBrowser.PopupMouseEnter(Object sender, MouseEventArgs e) in f:\projects\github\CefSharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 1187
       at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       at System.Windows.MouseOverProperty.FireNotifications(UIElement uie, ContentElement ce, UIElement3D uie3D, Boolean oldValue)
       at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
       at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
       at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
       at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
       at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
       at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
       at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
       at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.MouseDevice.Synchronize()
       at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
       at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException: 
```

For reference you can use `custom://cefsharp/TooltipTest.html` for testing purposes, their are drop downs on that page.

I don't have time to look into this further, if you have time, download the source and debug the problem yourself.

**Comment by goeranbarz** [comment]
Thank you for your help with the stack trace. As the last cefsharp related call in this code in ChromiumWebBrowser.PopupMouseEnter I could build a local patch for me which catches the exception. This might not be the optimal solution, but it fixes the problem:

`

        protected void PopupMouseEnter(object sender, MouseEventArgs e)
        {
            Focus();
            try
            {
                Mouse.Capture(this);
            }
            catch (System.ComponentModel.Win32Exception)
            {
            }
        }
`

**Comment by amaitland** [comment]
Looks like a bug in `WPF` http://stackoverflow.com/questions/37028182/exception-the-operation-completed-successfully-raising-property-changed-event

**Comment by amaitland** [comment]
Limited testing suggests that a few tweaks to Mouse.Capture - changes are in https://github.com/cefsharp/CefSharp/commit/21b9eb601e3425af10879b2b8619478f059137ca

**Comment by skhilliard** [comment]
I got build 55.0.0-ci2059 from https://www.myget.org/gallery/cefsharp.  Unfortunately, this bug still persists.
