### ISSUE TITLE
Insufficient memory to continue the execution - WPF

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#1759]
Hi Team,

I was faced the blow error in my application and I don't aware to know about cause of this issue. Shall we know the reason for this issue? We are using Cef browser Version 45.0.0.0.

**Application Error - Insufficient memory to continue the execution of the program. at System.Windows.Media.Imaging.WriteableBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette)
at CefSharp.Wpf.Rendering.WritableBitmapInfo.CreateBitmap()
at CefSharp.Wpf.ChromiumWebBrowser.<>c__DisplayClass13.<CefSharp.Internals.IRenderWebBrowser.InvokeRenderAsync>b__12()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).** 

Technical details

CefSharp Version: 45.0.0.0
Operating System: Windows 10 / Windows 8
x86/x64: x86/x64
Platform :  WPF

Regards,
Arun

**Comment by amaitland** [comment]
> Shall we know the reason for this issue? We are using Cef browser Version 45.0.0.0.

The version your using is not supported. `51.0.0` is the current supported version.

Hosting the `WinForms` version in `WPF` is often the best approach.

Further questions ask on https://gitter.im/cefsharp/CefSharp# (As per the issue template).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by KatherineWinter** [comment]
I'm seeing this issue in v 75.1.142.0 with on Windows 10 with high DPI monitors.
