### ISSUE TITLE
System.IO.FileNotFound from Cef.Initialize (?)

### ISSUE THREAD

**Issue by ezrasp** [cefsharp/CefSharp#1761]
hello, i'm having trouble deploying a CefSharp WinForms application. it works fine on my development machine but crashes on the target machine. the cause seems to be an uncaught `System.IO.FileNotFoundException`, but i can't figure out what files are missing, or from where. (this seems very similar to issue #1343.) i also can't seem to catch the exception in the program.

no `debug.log` is produced by CEF; maybe it doesn't far enough along.

the TestApp program from cefbuilds.com runs fine on the same machine.

i've duplicated the behavior in a minimal test application, and using the CefSharp.MinimalExample (commit ac451f78d0f5d6d4b81d1cbd1ad41d1a1670d9ff)

both development and deployment machines are running windows 8.1 pro, 64-bit OS and processor, and my dev environment is Visual Studio 2013 Ultimate. 

CefSharp is installed from NuGet:
Runtime Version: v4.0.30319
Version: 51.0.0.0

here's the complete Program.cs from my minimal test application

```
using System;
using System.Windows.Forms;

using CefSharp;
using NLog;

namespace WebFormTest
{
    static class Program
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        [STAThread]
        static void Main()
        {

            logger.Debug("entered Main");

             Application.EnableVisualStyles();
             Application.SetCompatibleTextRenderingDefault(false);

             logger.Debug("finished app setup");

             try
             {
             	// crash seems to occur here
                 Cef.Initialize(new CefSettings(), shutdownOnProcessExit: false, performDependencyCheck: true);
             }
             catch (Exception ex)
             {
                 // strangely, never gets here... where is the exception?
                 string msg = "CEF init failed with exception: " + ex.ToString();
                 MessageBox.Show(msg);
                 logger.Error(msg);
             }

            // never gets here
             logger.Debug("finished initializing CEF");

             try
             {
                 BrowserForm browser = new BrowserForm();
                 Application.Run(browser);
             }
             catch (Exception ex)
             {
                 string msg = "browser creation failed with exception: " + ex.ToString();
                 MessageBox.Show(msg);
                 logger.Error(msg);
             }

             /// never gets here (sanity check)
             MessageBox.Show("hello");
        }
    }
}

```

and here's the event log from the crash in  CefSharp.MinimalExample.WinForms.exe (it is identical for the minimal test program):
```
Log Name:      Application
Source:        Application Error
Date:          7/29/2016 1:16:00 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      VIDEOWALL
Description:
Faulting application name: CefSharp.MinimalExample.WinForms.exe, version: 1.0.0.0, time stamp: 0x579bb90f
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54505737
Exception code: 0xe0434352
Fault offset: 0x0000000000008b9c
Faulting process id: 0xe9c
Faulting application start time: 0x01d1e9d6062dd2e3
Faulting application path: C:\Users\spvideowall\Desktop\CefSharpExample\Debug\CefSharp.MinimalExample.WinForms.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 43e06254-55c9-11e6-8267-00032d2dcce0
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-29T20:16:00.000000000Z" />
    <EventRecordID>2481</EventRecordID>
    <Channel>Application</Channel>
    <Computer>VIDEOWALL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>CefSharp.MinimalExample.WinForms.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>579bb90f</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17415</Data>
    <Data>54505737</Data>
    <Data>e0434352</Data>
    <Data>0000000000008b9c</Data>
    <Data>e9c</Data>
    <Data>01d1e9d6062dd2e3</Data>
    <Data>C:\Users\spvideowall\Desktop\CefSharpExample\Debug\CefSharp.MinimalExample.WinForms.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>43e06254-55c9-11e6-8267-00032d2dcce0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          7/29/2016 1:16:00 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      VIDEOWALL
Description:
Application: CefSharp.MinimalExample.WinForms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at CefSharp.MinimalExample.WinForms.Program.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-29T20:16:00.000000000Z" />
    <EventRecordID>2480</EventRecordID>
    <Channel>Application</Channel>
    <Computer>VIDEOWALL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: CefSharp.MinimalExample.WinForms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at CefSharp.MinimalExample.WinForms.Program.Main()

</Data>
  </EventData>
</Event>
```

and finally, here is the contents of Debug folder for the MinimalExample:
```
07/28/2016  08:49 AM         2,749,972 cef.pak
07/28/2016  08:50 AM         1,065,984 CefSharp.BrowserSubprocess.Core.dll
07/28/2016  08:50 AM             8,192 CefSharp.BrowserSubprocess.exe
07/28/2016  08:50 AM         1,578,496 CefSharp.Core.dll
07/28/2016  08:50 AM            49,366 CefSharp.Core.xml
07/28/2016  08:50 AM           162,816 CefSharp.dll
07/29/2016  01:14 PM            97,792 CefSharp.MinimalExample.WinForms.exe
07/28/2016  08:47 AM               146 CefSharp.MinimalExample.WinForms.exe.config
07/29/2016  01:14 PM            38,400 CefSharp.MinimalExample.WinForms.pdb
07/28/2016  08:50 AM            21,504 CefSharp.WinForms.dll
07/28/2016  08:50 AM            37,795 CefSharp.WinForms.xml
07/28/2016  08:50 AM           360,173 CefSharp.xml
07/28/2016  08:49 AM           146,067 cef_100_percent.pak
07/28/2016  08:49 AM           235,262 cef_200_percent.pak
07/28/2016  08:49 AM         4,409,164 cef_extensions.pak
07/28/2016  08:49 AM         2,106,216 d3dcompiler_43.dll
07/28/2016  08:49 AM         4,470,976 d3dcompiler_47.dll
07/28/2016  08:49 AM         4,740,603 devtools_resources.pak
07/28/2016  08:49 AM        10,127,152 icudtl.dat
07/28/2016  08:49 AM        69,740,032 libcef.dll
07/28/2016  08:49 AM            94,208 libEGL.dll
07/28/2016  08:49 AM         2,323,456 libGLESv2.dll
07/28/2016  08:50 AM    <DIR>          locales
07/28/2016  08:49 AM           415,533 natives_blob.bin
07/28/2016  08:49 AM           662,124 snapshot_blob.bin
07/28/2016  08:49 AM           279,552 widevinecdmadapter.dll
```

and `locales` contains a long list of `.pak`s as expected.

i must be missing something.. but what? any help is appreciated. and, my apologies if this is an in appropriate use of the issue tracker.

**Comment by ezrasp** [comment]
oh, i also tried skipping the dependency check, same result
```
Cef.Initialize(new CefSettings(), shutdownOnProcessExit: false, performDependencyCheck: false);
```

**Comment by ezrasp** [comment]
apologies! i was missing the vc++ runtime redistribution, as clearly mentioned in the FAQ. sorry for the noise.
