### ISSUE TITLE
"The added or subtracted value results in an un-representable DateTime" occurring in 63.0.1

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#2283]
Version: 63.0.1
Architecture: x86
Operating System: Windows 2012

A website that sets a cookie with a large epoch. Causes the error: 

The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at System.DateTime.AddTicks(Int64 value)
   at System.DateTime.Add(Double value, Int32 scale)
   at CefSharp.Internals.DateTimeUtils.FromCefTime(Double epoch)
   at CefSharp.ResourceHandlerWrapper.GetCookie(ResourceHandlerWrapper* , CefStructBase<CefCookieTraits>* cookie)
   at CefSharp.ResourceHandlerWrapper.CanGetCookie(ResourceHandlerWrapper* , CefStructBase<CefCookieTraits>* cookie)

I have released a fix for this in #2282 but I thought I should mention it here to make it clear that the pull request is for a bug fix.

**Comment by amaitland** [comment]
Do you have an example that reproduces the problem? Some JavaScript that creates a problematic cookie?

**Comment by GrabzIt** [comment]
Unfortunately not, I take ~100,000 of screenshots a day of different websites and I keep on seeing this error in the software log error. It just occurred again ten minutes ago. I have looked at the websites that were produced on that server at the time and none of them seemed to recreate the issue. Which makes me think it is perhaps an intermittent error maybe due to some in accurate data coming from CEF?

I have came across this problem before with cookie expiry dates here: https://github.com/cefsharp/CefSharp/commit/93b08f1c126b41b4489182db5581c820d9b88b4f

**Comment by amaitland** [comment]
Be interesting to see what data CEF is returning, are you in a position to add some logging?

See https://github.com/cefsharp/CefSharp/blob/f93a387593f3dfc34c5165e9ea07cf3c11f7c221/CefSharp.Core/SchemeHandlerFactoryWrapper.h#L60 for an example

**Comment by GrabzIt** [comment]
I am not sure where I would put the logging for this as the epoch used in the method is coming from the CefTime.GetDoubleT method, which isn't exposed.

I have seen cookies on what I suspected was the problem website with expired dates of 31/12/9999 23:59:59 however I don't know how these cookies were set because when I tried to set it in PHP or JavaScript it would turn it into a session cookie after 2030!

It maybe a timezone issue that is causing the epoch to go over the maxdate in some circumstances. If the GetDoubleT method is assuming or inferring a timezone.

**Comment by amaitland** [comment]
I was curious to see what epoch values are being returned. Sounds like we should revert to manually constructing the CEF datetime, bit of a shame as the epoch code is much cleaner. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Core/Internals/CookieVisitor.cpp#L28

Probably have to switch to an entirely C++ based solution to reduce code duplication.

**Comment by GrabzIt** [comment]
I agree its a shame, but I think you are right there is no sense in detecting invalid date times in both C++ and C#.

**Comment by amaitland** [comment]
@GrabzIt I've rewritten the date conversion, I would ideally like a pure `C++` solution, that can come later though.

See https://github.com/cefsharp/CefSharp/commit/5e6addc0c9601ee91601f52078c8f6f32a1b4b99 and let me know what you think.

**Comment by GrabzIt** [comment]
That should solve the problem :-D thanks for all your help!

**Comment by amaitland** [comment]
Change was merged into `cefsharp/63` branch and will be part of the `63.0.2` release which should come in the next few days 😄

**Comment by GrabzIt** [comment]
Awesome!! Thanks so much :-D
