### ISSUE TITLE
Upgrade GitLink

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2395]
Currently we're using 2.3.0 and are executing `GitLink` from the command line, newer versions (`3.1.0` at time of writing) support integration into the project directly through `Nuget/MsBuild`.

https://github.com/GitTools/GitLink/blob/develop/README.md#nugetmsbuild-integration

- [ ] Install `GitLink` into the relevant packages
- [ ] Remove GitLink from `build.ps1`.

**Comment by amaitland** [comment]
https://github.com/dotnet/sourcelink

Potentially we should switch to the new sourcelink. 

MS is planning on launching it's own symbol server and adding first class support for remote debugging, this may impact on how the packages are structured. 

https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements

**Comment by amaitland** [comment]
https://blog.nuget.org/20180501/Welcoming-SymbolSource-to-Dot-Net-Foundation.html

**Comment by ray007** [comment]
Is this the right place to mention my gitlink problem when building with `build.ps1`?
I'm getting
```
Downloading GitLink

Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
At J:\devel\cef\CefSharp\build.ps1:330 char:13
+             $client.DownloadFile('https://github.com/GitTools/GitLink/releases/d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException


GitLink working dir : J:\devel\cef\CefSharp

. : The term 'J:\devel\cef\CefSharp\.\nuget\GitLink.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At J:\devel\cef\CefSharp\build.ps1:337 char:7
+     . $gitlink $WorkingDir -f CefSharp3.sln -u https://github.com/CefSharp/CefSh ...
+       ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (J:\devel\cef\Ce...get\GitLink.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term 'J:\devel\cef\CefSharp\.\nuget\GitLink.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At J:\devel\cef\CefSharp\build.ps1:338 char:7
+     . $gitlink $WorkingDir -f CefSharp3.sln -u https://github.com/CefSharp/CefSh ...
+       ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (J:\devel\cef\Ce...get\GitLink.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
The rest works, so it's not really a problem...

**Comment by ray007** [comment]
Very strange. If I download `GitLink` 2.3 and put it in the nuget-directoy, I get the following errors:
```
GitLink working dir : J:\devel\cef\CefSharp

GitLink v2.3.0.0
================

Arguments: J:\devel\cef\CefSharp -f CefSharp3.sln -u https://github.com/CefSharp/CefSharp -c Release -p x64 -ignore CefSharp.Example CefSharp.Wpf.Example CefSharp.OffScreen.Example CefSharp.WinForms.Example

Could not parse command line parameter 'CefSharp.Wpf.Example'.
An unexpected error occurred | [GitLinkException] GitLink.GitLinkException: Could not parse command line parameter 'CefSharp.Wpf.Example'.
   at GitLink.ArgumentParser.ParseArguments(List`1 commandLineArguments, IProviderManager providerManager)
   at GitLink.Program.Main(String[] args)
GitLink v2.3.0.0
================

Arguments: J:\devel\cef\CefSharp -f CefSharp3.sln -u https://github.com/CefSharp/CefSharp -c Release -p x86 -ignore CefSharp.Example CefSharp.Wpf.Example CefSharp.OffScreen.Example CefSharp.WinForms.Example

Could not parse command line parameter 'CefSharp.Wpf.Example'.
An unexpected error occurred | [GitLinkException] GitLink.GitLinkException: Could not parse command line parameter 'CefSharp.Wpf.Example'.
   at GitLink.ArgumentParser.ParseArguments(List`1 commandLineArguments, IProviderManager providerManager)
   at GitLink.Program.Main(String[] args)
```
But as I said: the end result is working, so no real trouble here.

**Comment by amaitland** [comment]
Superseded by #3036

**Comment by amaitland** [comment]
Slight change of plan. `GitLink` was upgraded in #3311

We now use the `Nuget` packages instead of calling `GitLink.exe` manually.
