### ISSUE TITLE
Build fails with System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by merceyz** [cefsharp/CefSharp#2508]
- **What version of the product are you using?**
    - Master at 6602977496ea4aed649b8e5a3273331a01a46865

- **What architecture x86 or x64?**
    - Applies to both

- **On what operating system?**
    - Windows 7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - Applies to all

- **What steps will reproduce the problem?**
    - Clone a clean version of the repo
    - Restore all nuget packages
    - Build Solution

- **What is the expected output? What do you see instead?**
    - Build should succeed instead it fails with this message:
```
9>------ Build started: Project: CefSharp.Wpf.Example, Configuration: Debug x86 ------
10>------ Build started: Project: CefSharp.WinForms.Example, Configuration: Debug x86 ------
11>------ Build started: Project: CefSharp.OffScreen.Example, Configuration: Debug x86 ------
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception: 
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.LoadAssemblyWithRedirects(AssemblyName name)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.ResolveAssembly(String assemblyDisplayName, Assembly requestingAssemblyOpt)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Roslyn.Utilities.CorLightup.Desktop.AssemblyResolveWrapper.Stub(Object sender, Object resolveEventArgs)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : WRN: Assembly binding logging is turned OFF.
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : Note: There is some performance penalty associated with assembly bind failure logging.
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.GetPipeNameForPathOpt(String compilerExeDirectory)
11>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception: 
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.LoadAssemblyWithRedirects(AssemblyName name)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.ResolveAssembly(String assemblyDisplayName, Assembly requestingAssemblyOpt)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Roslyn.Utilities.CorLightup.Desktop.AssemblyResolveWrapper.Stub(Object sender, Object resolveEventArgs)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : WRN: Assembly binding logging is turned OFF.
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : Note: There is some performance penalty associated with assembly bind failure logging.
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.GetPipeNameForPathOpt(String compilerExeDirectory)
10>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
9>CefSharp\CefSharp.Wpf.Example\App.xaml.cs(34,17,34,38): warning CS0162: Unreachable code detected
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception: 
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : File name: 'System.Security.Principal.Windows, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.LoadAssemblyWithRedirects(AssemblyName name)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution.ResolveAssembly(String assemblyDisplayName, Assembly requestingAssemblyOpt)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Roslyn.Utilities.CorLightup.Desktop.AssemblyResolveWrapper.Stub(Object sender, Object resolveEventArgs)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : WRN: Assembly binding logging is turned OFF.
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : Note: There is some performance penalty associated with assembly bind failure logging.
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.GetPipeNameForPathOpt(String compilerExeDirectory)
9>CefSharp\packages\Microsoft.Net.Compilers.2.7.0\tools\Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
```

- **Please provide any additional information below.**
```
Microsoft Visual Studio Community 2017
Version 15.8.3
VisualStudio.15.Release/15.8.3+28010.2019
Microsoft .NET Framework
Version 4.7.02558
```

**Comment by amaitland** [comment]
Seems like https://stackoverflow.com/questions/52068480/build-error-roslyn-msb3883-unexpected-exception-system-io-filenotfoundexcept is for a similar issue. Not really a helpful answer. Maybe upgrading `Microsoft.Net.Compilers` is worth doing.

**Comment by merceyz** [comment]
> I'm not seeing any errors and when I go to update VS it doesn't show any new version waiting for install. Are you using a Preview version?

Shouldn't be https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.8.3

> Maybe upgrading Microsoft.Net.Compilers is worth doing.

That also solved it, PR updated

**Comment by amaitland** [comment]
Great, thanks 👍
