### ISSUE TITLE
Invoking a C# object from JS with a string containing an invalid Unicode point, leaves ServiceChannel in a Faulted state.

### ISSUE THREAD

**Issue by kiewic** [cefsharp/CefSharp#2764]
- **What version of the product are you using?**

Building master branch commit 002edfb058ee5feafc705453ff7f868dd6bd2fa6.

- **What architecture x86 or x64?**

x64

- **On what operating system?**

Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

I created a repro in my local fork: https://github.com/kiewic/CefSharp/commit/a94a027aad7966ff77120811e42131c0af237e19

1. Invoke a C# object with an invalid character, e.g., `"\udc11"`
2. First call fails with: `Uncaught Error: System.Text.EncoderFallbackException: Unable to translate Unicode character \uDC11 at index 0 to specified code page.`
3. Subsequent calls fail with: `Uncaught Error: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.`
4. For some reason I have not been able to figure out yet, the renderer process will crash at some point after this.

- **What is the expected output? What do you see instead?**

Any of these:

1. Not a crash, and a way to restart the channel.
2. Remove invalid code points.
3. Invalid unicode characters are transmitted to C# anyway.

- **Please provide any additional information below.**

```
Uncaught Error: System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 0 to specified code page.

Server stack trace: 
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount)
   at System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars(Char* chars, Int32 charCount, Byte[] buffer, Int32 offset)
   at System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(Char* chars, Int32 charCount)
   at System.Xml.XmlBinaryNodeWriter.WriteText(String value)
   at System.Xml.XmlBaseWriter.WriteString(String value)
   at System.Runtime.Serialization.StringDataContract.WriteXmlValue(XmlWriterDelegator writer, Object obj, XmlObjectSerializerWriteContext context)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
   at WriteArrayOfanyTypeToXml(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext , CollectionDataContract )
   at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameterPart(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameter(XmlDictionaryWriter writer, PartInfo part, Object graph)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameters(XmlDictionaryWriter writer, PartInfo[] parts, Object[] parameters)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, MessageVersion version, String action, MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BufferedMessageWriter.WriteMessage(Message message, BufferManager bufferManager, Int32 initialOffset, Int32 maxSizeQuota)
   at System.ServiceModel.Channels.BinaryMessageEncoderFactory.BinaryMessageEncoder.WriteMessage(Message message, Int32 maxMessageSize, BufferManager bufferManager, Int32 messageOffset)
   at System.ServiceModel.Channels.FramingDuplexSessionChannel.EncodeMessage(Message message)
   at System.ServiceModel.Channels.FramingDuplexSessionChannel.OnSendCore(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.OutputChannel.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IBrowserProcess.CallMethod(Int64 objectId, String name, Object[] parameters)
   at CefSharp.JavascriptMethodHandler.Execute(JavascriptMethodHandler* , CefStringBase<CefStringTraitsUTF16>* name, scoped_refptr<CefV8Value>* object, vector<scoped_refptr<CefV8Value>\,std::allocator<scoped_refptr<CefV8Value> > >* arguments, scoped_refptr<CefV8Value>* retval, CefStringBase<CefStringTraitsUTF16>* exception) in c:\projects\cefsharp\cefsharp.browsersubprocess.core\javascriptmethodhandler.cpp:line 15
    at HTMLButtonElement.<anonymous> (file:///index.html:70:62)



index.html:63 Uncaught Error: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IBrowserProcess.CallMethod(Int64 objectId, String name, Object[] parameters)
   at CefSharp.JavascriptMethodHandler.Execute(JavascriptMethodHandler* , CefStringBase<CefStringTraitsUTF16>* name, scoped_refptr<CefV8Value>* object, vector<scoped_refptr<CefV8Value>\,std::allocator<scoped_refptr<CefV8Value> > >* arguments, scoped_refptr<CefV8Value>* retval, CefStringBase<CefStringTraitsUTF16>* exception) in c:\projects\cefsharp\cefsharp.browsersubprocess.core\javascriptmethodhandler.cpp:line 15
    at HTMLButtonElement.<anonymous> (file:///index.html:63:62)
```

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

I think this does not apply, let me check.

P.S. is there any docs on how to run QUnit tests?

**Comment by amaitland** [comment]
> Building master branch.

In future please include the commit you are using. Whilst not relevant for this particular issue, it's still an ambiguous statement, `master` is always changing. Someone viewing this in three months time will be viewing a drastically different `master`.

> 1. Not a crash, and a way to restart the channel.

I have no objection to one being added, and a `PR` is welcome, I have no plans to add one. 

> 2\. Remove invalid code points.

This sounds like it would have a performance impact. Is there something stopping you sanitising the data in `javascript` before it's sent? I've not seen any similar requests from others, so from my point of view the rewards of implementing such a feature for one single use case just aren't there.

> 3\. Invalid unicode characters are transmitted to C# anyway.

Unlikely this isn't feasible as it's `.NET` doing the parsing. Do you have any links that indicate it's possible?

> P.S. is there any docs on how to run QUnit tests?

Just open `custom://cefsharp/BindingTest.html` in either the `WPF` or `WinForms` examples. The `WPF` example has a menu item already.

Overall the `Sync` version that uses `WCF` isn't being actively maintained, if it was feasible to remove the feature I would.

**Comment by amaitland** [comment]
I will be at some point in the near future be added new features to the `Async` version to expand it's capabilities. If you have a particular use case that's not supported in the `Async` version then by all means jump on https://gitter.im/cefsharp/CefSharp to discuss your requirements.

**Comment by kiewic** [comment]
> Overall the `Sync` version that uses `WCF` isn't being actively maintained, if it was feasible to remove the feature I would.

Interesting, so if I use Async methods, these ones do not use WCF, and they use Chromium IPC instead?

**Comment by amaitland** [comment]
Correct

**Comment by amaitland** [comment]
Closing this as I have no current plans to make improvements to the `WCF` implementation. You or anyone else is obviously welcome to submit a `PR` with improvements you would like to see.

> It's recommended that anyone creating a new application use the Async version as it's under active development.

As stated in https://github.com/cefsharp/CefSharp/wiki/General-Usage#sync-javascript-binding-jsb it's recommended that anyone developing a new application use the `Async` binding.

Progress on further improvements to the `Async Binding` implementation can be traced at https://github.com/cefsharp/CefSharp/issues/2765
