### ISSUE TITLE
CefSharp.BrowserSubprocess.exe is crashing after long run

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#2968]
- **What version of the product are you using?**
Nuget 75.1.142.0

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Some of our clients have been reporting that after running our WPF app for a longer time (more than a day), the embedded web view starts to be unresponsive, e.g. it is no longer clickable and acts like a screenshot of the embedded web. We were able to replicate this issue also on our development machine - we left the app running during the night and in the morning we encountered the same issue - the window with the embedded web was unresponsive (other windows in the app were not affected) and the host `CefSharp.BrowserSubprocess.exe` process didn't longer exist. We checked the .NET logs alco the CefSharp logs (LogSeverity set to "warning") and didn't find anything suspicious there. But we were able to found errors in system Event Viewer reporting the crash (see the "stack trace" section).

We were using CefSharp in our WPF app for many years without issues and these issues started after we've updated the CefSharp from the version 57.0.0 to the 73.1.13 (and are still present in the version 75.1.14)

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
Output from the system Evens Viewer:
```
Application: CefSharp.BrowserSubprocess.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Runtime.InteropServices.SEHException at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*) at CefSharp.BrowserSubprocess.SubProcess.Run() at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```

```

CefSharp.BrowserSubprocess.exe 
   75.1.142.0 
   5d7609b3 
   KERNELBASE.dll 
   10.0.17134.1067 
   e94e2b6e 
   e0000008 
   00114592 
   1fa0 
   01d593202eb33eed 
   C:\Users\Dominik Palo\AppData\Local\Slido\Slido Switcher\CefSharp.BrowserSubprocess.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   f2598408-6c38-46a4-b94e-7dceacf7a959

```

Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
noting special, just a few
`WARNING:dns_config_service_win.cc(672)] Failed to read DnsConfig.`
`ERROR:browser_process_sub_thread.cc(221)] Waited 35 ms for network service`
entries - according to the timestamps not related to the subprocess crash.

**Comment by amaitland** [comment]
> * What steps will reproduce the problem?

Think of this section as a set of details you give to someone external to your development team to reproduce the problem. Your bug report doesn't actually provide anything actionable, from an outsider looking in it basically equates to `Run my app for a long time and it crashes`.

Does the problem reproduce with https://github.com/cefsharp/CefSharp.MinimalExample?

Did you test with the `CEF Sample Application` as listed in the bug report template?

> * But we were able to found errors in system Event Viewer reporting the crash (see the "stack trace" section).

What you've provided isn't really a stacktrace. Enable crash reporting and get yourself a crash dump. See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#crash-reporting Making sure to [Load the symbols for libcef](https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis) to get a more meaningful exception.

**Comment by DominikPalo** [comment]
Thank you, I'm trying to get crash dumps, but it doesn't work for me as expected. I've added the `crash_reporter.cfg` file to my app dir:

```
[Config]
ExternalHandler=CefSharp.BrowserSubprocess.exe
RateLimitEnabled=false
MaxUploadsPerDay=0

[CrashKeys]
testkey_small1=small
testkey_small2=small
testkey_medium1=medium
testkey_medium2=medium
testkey_large1=large
```

After I start the app I can see the line `[1111/133540.078:INFO:crash_reporting.cc(219)] Crash reporting enabled for process: crashpad-handler`, but when I navigate to `chrome://crash` to simulate  a crash, my `CefSharp.BrowserSubprocess.exe` crashes (and it instantly starts again for a while) - unfortunately, the `c:\Users\Dominik\AppData\Local\CEF\User Data\Crashpad\reports\` folder is empty - no crash dumps.

I've also tried to use the provided `crash_server.py` script by starting the server on port 8066 and adding a line `ServerURL=http://localhost:8066` to my `crash_reporter.cfg`, but still no success - the server is correctly running on that port, but it doesn't receive anything after a crash.

Maybe is worth to mention that since I created the `crash_reporter.cfg`  I see this error during the start of the app:
```
[1111/134631.854:INFO:crash_reporting.cc(219)] Crash reporting enabled for process: crashpad-handler

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CefInitialize(CefMainArgs* , CefStructBase<CefSettingsTraits>* , scoped_refptr<CefApp>* , Void* )
   at CefSharp.Cef.Initialize(AbstractCefSettings cefSettings, Boolean performDependencyCheck, IApp cefApp) in c:\projects\cefsharp\cefsharp.core\cef.h:line 208
   at CefSharp.Cef.Initialize(AbstractCefSettings cefSettings) in c:\projects\cefsharp\cefsharp.core\cef.h:line 145
   at Slido_Switcher.App.Application_Startup(Object sender, StartupEventArgs e) in C:\Projects\slido-switcher-win\Slido Switcher\App.xaml.cs:line 128
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Slido_Switcher.App.Main()
[1111/134634.386:ERROR:registration_protocol_win.cc(84)] TransactNamedPipe: The pipe has been ended. (0x6D)
```

**Comment by amaitland** [comment]
> If "AppName" is set on Windows then crash report information (metrics, database and dumps) will be stored locally on disk under the "C:\Users\[CurrentUser]\AppData\Local\[AppName]\User Data"

You must set `AppName` to have the dumps generated locally on disk.

> I've also tried to use the provided `crash_server.py` script by starting the server on port 8066 and adding a line `ServerURL=http://localhost:8066` to my `crash_reporter.cfg` with no success - the server is correctly running on that port, but it doesn't receive anything after a crash.

Never tried the python server, no idea if it works.

> Maybe is worth to mention that since I created the `crash_reporter.cfg` I see this error during the start of the app:

The configuration is likely incorrect or there is a bug in `CEF`.

I've enabled crash reporting in the `MinimalExample` in commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/ac87ce9b5a9aa414fa1c9175fb83834fddff5ba7 

Crash reports are generated as expected.

> * e.g. it is no longer clickable and acts like a screenshot of the embedded web

Try the `chrome://gpucrash` test, it sounds like the `GPU Process` has crashed.
