### ISSUE TITLE
WinForms - ArgumentNullException: cannot be null Parameter name: browserSettings

### ISSUE THREAD

**Issue by E024** [cefsharp/CefSharp#2979]
- **What version of the product are you using?
    - 75.1.143
- **What architecture x86 or x64?**
     - x86
- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - WinForms
- **What steps will reproduce the problem?**
    - I cannot reproduce this problem systematically.

- **What is the expected output? What do you see instead?**
    - Getting a NullReferenceException at CefSharp.ManagedCefBrowserAdapter.CreateBrowser(IWindowInfo windowInfo, BrowserSettings browserSettings, RequestContext requestContext, String address)
- **Please provide any additional information below.**
    - ************** Exception Text **************
System.ArgumentNullException: cannot be null
Parameter name: browserSettings
   at CefSharp.ManagedCefBrowserAdapter.CreateBrowser(IWindowInfo windowInfo, BrowserSettings browserSettings, RequestContext requestContext, String address)
   at CefSharp.WinForms.ChromiumWebBrowser.CreateBrowser()
   at CefSharp.WinForms.ChromiumWebBrowser.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - There are debug.log logs, but I'm not sure if this is the exception.
    - like this
    -[1010/183659.420:ERROR:gles2_cmd_decoder.cc(18524)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[1010/183659.420:ERROR:gles2_cmd_decoder.cc(10797)] [.DisplayCompositor]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
 [1127/133513.734:ERROR:browser_process_sub_thread.cc(221)] Waited 32 ms for network service
[1127/133513.804:ERROR:process_info.cc(620)] range at 0xdfe000, size 0x2000 partially unreadable
[1127/133513.805:ERROR:process_info.cc(620)] range at 0x8ade000, size 0x2000 partially unreadable
[1127/133513.806:ERROR:process_info.cc(620)] range at 0x15ece000, size 0x2000 partially unreadable
[1127/145129.708:ERROR:browser_process_sub_thread.cc(221)] Waited 21 ms for network service
[1127/161455.673:ERROR:broker_win.cc(55)] Error reading broker pipe: 管道已结束。 (0x6D)
[1127/161455.674:ERROR:command_buffer_proxy_impl.cc(94)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed

**Comment by amaitland** [comment]
Are you setting the [BrowserSettings](http://cefsharp.github.io/api/75.1.x/html/P_CefSharp_WinForms_ChromiumWebBrowser_BrowserSettings.htm) property?

If you are setting `browser.BrowserSettings = nulll` at some point then this could easily be a bug in your code.

I've seen no other reports and without a way to reproduce this there is nothing I can do.

**Comment by E024** [comment]
> Are you setting the [BrowserSettings](http://cefsharp.github.io/api/75.1.x/html/P_CefSharp_WinForms_ChromiumWebBrowser_BrowserSettings.htm) property?
> 
> If you are setting `browser.BrowserSettings = nulll` at some point then this could easily be a bug in your code.
> 
> I've seen no other reports and without a way to reproduce this there is nothing I can do.

I didn't set this property anywhere in my project

Thank you for your answer, because I can't reproduce this problem by myself, but this happened by chance, and feedback by the way.

**Comment by amaitland** [comment]
As you are currently the only one able to reproduce this problem there really isn't anything I can do without more information. If you can provide a means of reproducing the problem then we can look at fixing it.

Make sure you are creating and disposing of the `ChromiumWebBrowser` instance on the `UI Thread`.

**Comment by E024** [comment]
- Make sure you are creating and disposing of the ChromiumWebBrowser instance on the UI Thread.
  - ChromiumWebBrowser is not operating in a non-ui thread
- OK, thank you, I continue to try to reproduce, and then reply again, thanks again.

**Comment by amaitland** [comment]
An example of your code would be a helpful start, are you using the designer,  which constructor are you using, anything that might give some clue. 

For some inspiration https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/#golden-rule is well worth a read. The principles are the sample applies when writing bug reports.
