### ISSUE TITLE
After Updating Windows 10 x64 to Feature update 2004, CefSharp x86 WPF is giving an error.

### ISSUE THREAD

**Issue by codefinity** [cefsharp/CefSharp#3246]
- **What version of the product are you using?**

    Nuget CefSharp WPF - 84.4.10, Visual Studio 2019 - Community, .Net 4.8

- **What architecture x86 or x64?**
    Windows 10 x64,  CefSharp x86
    
- **On what operating system?**
    Win10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**

1. Run the CefSharp WPF Minimal Example on System with windows feature update prior to 2004  (ie Windows 10 Feature Update1903). The WPF Minimal Example works without any issues.

1. Run the CefSharp WPF Minimal Example on System with windows feature update 2004. The WPF Minimal Example gives the following error:

"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

 **Does the problem reproduce using the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)?** 

Yes

- **What is the expected output? What do you see instead?**

**Expected Output:** The CefSharp browser should be displayed when the project runs.

**What we see:** An error popup with the following message:

"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

- **Please provide any additional information below.**

System.IO.FileNotFoundException
  HResult=0x8007007E
  Message=Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
  Source=CefSharp.MinimalExample.Wpf
  StackTrace:
   at CefSharp.MinimalExample.Wpf.App..ctor() in H:\CEFSHARP EXAMPLE\CefSharp.MinimalExample\CefSharp.MinimalExample.Wpf\App.xaml.cs:line 34
   at CefSharp.MinimalExample.Wpf.App.Main()

- **Does this problem also occur in the `CEF` Sample Application**
No

**Comment by amaitland** [comment]
How many machines have you tested on? I haven't had any other reports,  so are you sure this isn't something specific to your environment? 

Does the WinForms example behave the same?

Please condense the title, it's too long.

**Comment by codefinity** [comment]
@amaitland we have tested it on 2 **Windows 10** machines with **Feature Update 2004**, and in both the machines it threw the error.

Then we have tested it on 2 **Windows 10** machines with **Feature Update 1903**, and it worked fine.

Give me some time, I will test the WinForms example and get back.

**Comment by amaitland** [comment]
What version of cefclient did you tested with? What command line args did you use for testing cefclient? 

As I said there haven't been any other reports. What you are describing sounds more like Windows feature update has broken something than a problem with CefSharp. 

What VC++ Version do you have installed?

**Comment by codefinity** [comment]
@amaitland Thaks for your response.

1. **We have tested the WinForms Minimal example on Windows 10 x64 with CefSharp x86 and it is giving the same error**

"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found."

2. **Version of CefClient we tested on:**

CEF 84.3.10+ga46056b+chromium-84.0.4147.105 / Chromium 84.0.4147.105

**Command Line Argument used to test:**

```
cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
```

3. **"As I said there haven't been any other reports. What you are describing sounds more like Windows feature update has broken something than a problem with CefSharp."**

Updating Windows to the latest Version has stopped CefSharp WPF x86 from working.

4. **VC++ Version installed?**

Microsoft Visual C++ 2015-2019 Redistributable(x64) - 14.27.29016

Microsoft Visual C++ 2015-2019 Redistributable(x86) - 14.23.27820

**Comment by amaitland** [comment]
Have you installed all the optional updates for Win 10 2004? Reviewed the Windows 10 2004 change log/release notes?

I don't have the free space to upgrade to 2004 so I'm able to test myself. I'd expect to have reports from multiple sources if this was a widespread issue.

**Comment by amaitland** [comment]
I built a computer and installed Windows 10 2004 x64 on an old Optiplex 9010. Both the x86 and x64 versions of the minimal example work as expected. Fresh install of VS 2019 Community,  not sure of the exact build number. 

I don't believe this is a bug and would appear to be isolated to your environment. Try reinstalling VC++ . Run system file checker. Temporary disable any antivirus. 

I'll leave this open for now.

**Comment by jozefizso** [comment]
We have similar issue at some customers' Windows 10 1909 64-bit (Windows 10.0.18363):

```
Resolving assembly '"CefSharp.Core, Version=84.4.10.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138"'.
System.IO.FileLoadException: A procedure imported by 'CefSharp.Core.dll' could not be loaded.
```

We cannot replicate this on our Windows 10 1909 installations, but I can replicate it on clean Windows 7 SP1 64-bit installation with **Visual C++ 2019** installed. When I use **Dependencies** app it shows this error:

```
The procedure entry point _o_memset could not be located in the dynamic link library api-ms-win-crt-private-l1-1-0.dll.
```

We installed VC++ Runtime from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

![Win7 QA x64-2020-10-08-11-46-01](https://user-images.githubusercontent.com/287778/95442595-e09d2100-095b-11eb-8497-b880e673e824.png)

**Comment by amaitland** [comment]
Reinstalling VC++ would be the first thing I'd try. Chances as this is a missing dll causing problems. 

As it stands this will be closed as there's nothing actionable from a bug point of view.

**Comment by codefinity** [comment]
This Issue got resolved after Microsoft sent few more updates and optional updates after its Feature update 2004.
