### ISSUE TITLE
WPF - OnPaint System.IO.IOException

### ISSUE THREAD

**Issue by plasmarebel** [cefsharp/CefSharp#3308]
- **What version of the product are you using?**
    - 85.3.130

- **What architecture x86 or x64?**
    x86
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    - Opening new browsers after several hours of usage, will cause my program to crash.

- **What is the expected output? What do you see instead?**
    - Expected output is to open up a new browser after one is disposed, but instead program crashes.

- **Please provide any additional information below.**
    Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(Microsoft.Win32.SafeHandles.SafeMemoryMappedFileHandle, System.IO.MemoryMappedFiles.MemoryMappedFileAccess, Int64, Int64)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64, Int64, System.IO.MemoryMappedFiles.MemoryMappedFileAccess)
   at CefSharp.Wpf.Rendering.InteropBitmapRenderHandler.CreateOrUpdateBitmap(Boolean, CefSharp.Structs.Rect, IntPtr, Int32, Int32, System.Windows.Controls.Image, System.Windows.Size ByRef, System.IO.MemoryMappedFiles.MemoryMappedFile ByRef, System.IO.MemoryMappedFiles.MemoryMappedViewAccessor ByRef)
   at CefSharp.Wpf.Rendering.AbstractRenderHandler.OnPaint(Boolean, CefSharp.Structs.Rect, IntPtr, Int32, Int32, System.Windows.Controls.Image)
   at CefSharp.Wpf.ChromiumWebBrowser.OnPaint(Boolean, CefSharp.Structs.Rect, IntPtr, Int32, Int32)
   at CefSharp.Wpf.ChromiumWebBrowser.CefSharp.Internals.IRenderWebBrowser.OnPaint(CefSharp.PaintElementType, CefSharp.Structs.Rect, IntPtr, Int32, Int32)
   at <Module>.CefSharp.Internals.RenderClientAdapter.OnPaint(CefSharp.Internals.RenderClientAdapter, scoped_refptr<CefBrowser>, cef_paint_element_type_t, std.vector<CefRect,std::allocator<CefRect> >, Void, Int32, Int32)

**Comment by amaitland** [comment]
> * **What architecture x86 or x64?**
>   x86

Is your process `Large Address Aware`? This is a **must** when using a `32bit` version of `Chromium`. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#win32-out-of-memory

> * Opening new browsers after several hours of usage, will cause my program to crash.

Your process is out of memory, the `ChromiumWebBrowser` instance is unable to allocate the memory required to buffer the bitmap used to represent the browser.

A few of the possible options are (there's probably more, I'm just keeping this short for now).

1) Your application is leaking memory
  There are some pretty common `WPF` memory leaks that can easily be avoided.
2) There's a leak in `CefSharp.Wpf.ChromiumWebBrowser` 
  I'm not aware of any currently and haven't had any other reports. Obviously it's possible. By all means run a memory profiler and report back.
3) The `Chromium` version you are using in combination with whatever browser features is leaking memory
  Version `85.3.130` is now outdated, version `86.0.241` is the current supported version. Please test with `86.0.241` (make sure your process is `Large Address Aware`.

---
You can integrate `CEF` directly into your applications message loop to avoid needing to create the buffer, the `CEF UI Thread` will be the same as your applications `UI Thread` and a direct update of the bitmap will be possible. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop

This will avoid allocating the buffer and reduce the memory required by `CefSharp`.

**Comment by plasmarebel** [comment]
No, my application was not LAA. I decided to move the application to x64 and will have my users test with the new bit version. I will run a memory profiler tonight and if the crashing issues are not fixed I will let you know.

**Comment by plasmarebel** [comment]
After switching to x64, I am now encountering a different error after around 4 hours of usage. I caught a large memory leak with a javascript function that allowed an extra hour of usage, but still crashes with the error below.

Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>.CefExecuteProcess(CefMainArgs, scoped_refptr<CefApp>, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.BrowserSubprocessExecutable.Main(System.Collections.Generic.IEnumerable`1<System.String>, CefSharp.RenderProcess.IRenderProcessHandler)
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by plasmarebel** [comment]
Here are the error event logs from the program crash:

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e0000008, exception address 00007FF9F5CAD759

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

You'll need to get a stack trace to workout what's actually going on, I'd suggest enabling `Crash Reporting` then downloading the `libcef.dll.pdb` that matches the version you are using. Some details in the link above.

All I can say is one of the sub processes crashed. Based on the limited info provided it's likely the render process crash with an out of memory exception. Poorly behaving javascript is a very common cause of render process out of memory exceptions. Are you sure there aren't more leaks in your javascript?

Have you tested with version `86.0.241`? Each version of `Chromium` brings it's own performance/memory utilisation characteristics.

**Comment by plasmarebel** [comment]
Something new started happening after I fixed some of the JavaScript leaks. I changed the log severity to critical and the log has this (ERROR:gl_utils.cc(316)] [.DisplayCompositor] GL_INVALID_OPERATION: Invalid mailbox name) for each of the browsers. Also users have been reporting CPU usage spikes when this occurs, leading to an eventual crash. 

Again, they also have these event logs

Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>.CefExecuteProcess(CefMainArgs, scoped_refptr<CefApp>, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.BrowserSubprocessExecutable.Main(System.Collections.Generic.IEnumerable`1<System.String>, CefSharp.RenderProcess.IRenderProcessHandler)
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])

**Comment by amaitland** [comment]
You can search the chromium source at https://source.chromium.org/chromium

As I said you'll need to get a stack trace.

**Comment by amaitland** [comment]
A quick search yields https://bugs.chromium.org/p/chromium/issues/detail?id=481398

Have you tested with Chrome? Other than upgrading to a newer version there is unlikely anything that can be done about this from a CefSharp point of view.

**Comment by amaitland** [comment]
The https://www.nuget.org/packages/CefSharp.Wpf.HwndHost/ package is intended to be a drop in replacement for the WPF control, it's effectively hosting a Win32 version of the browser in WPF. 

The Win32 implementation (used by WinForms and the hwndhost implementation) has better performance, and lower resource usage. 

I'd suggest testing with the hwndhost implementation, you'll at least avoid the overhead of buffering the images for display and the avoid the original problem you were experiencing. 

There's unlikely anything I can do about the chromium error you are seeing.
