### ISSUE TITLE
CefSharp.Internals.ClientAdapter.OnProcessMessageReceived NullReferenceException

### ISSUE THREAD

**Issue by snowball58** [cefsharp/CefSharp#3322]
**What version of the product are you using?**

85.3.130

**What architecture x86 or x64?**

x86

**On what operating system?**

Win10

**Are you using WinForms, WPF or OffScreen?**

WinForms

**What steps will reproduce the problem?**

We have not modified CefSharp or CEF in any way. The issue was encountered several hours into a "soak" of our product, which involved opening and closing browser instances at a high frequency over an extended period of time. This seems to be rare and difficult to reproduce.

**Please provide any additional information below.**

This appears to be the same error as this closed issue: [Issue](https://github.com/cefsharp/CefSharp/issues/2971)

System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter* , scoped_refptr* browser, scoped_refptr* frame, cef_process_id_t source_process, scoped_refptr* message)

**Comment by amaitland** [comment]
Can you provide a full stack trace please.

**Comment by snowball58** [comment]
Unfortunately, based on our logs, that appears the full stack trace.

Here is the full log of the error:

2020-12-14T22:18:37.4010000	tid=19	pid=10416	Application shut down due to unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter* , scoped_refptr<CefBrowser>* browser, scoped_refptr<CefFrame>* frame, cef_process_id_t source_process, scoped_refptr<CefProcessMessage>* message)

**Comment by amaitland** [comment]
Do you have the pdb next to the dll?

I need a stack trace or an example that reproduces the problem.

**Comment by snowball58** [comment]
I don't think there is much else I can provide. The error as posted above does contain the stack trace, but I understand that is not much to go on.

**Comment by amaitland** [comment]
Can you download libcef.dll.pdb and place it next to libcef.dll 

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis

The 85.3.13 x86 release symbols https://cef-builds.spotifycdn.com/cef_binary_85.3.13%2Bgcd6cbe0%2Bchromium-85.0.4183.121_windows32_release_symbols.tar.bz2

**Comment by amaitland** [comment]
With commit https://github.com/cefsharp/CefSharp/commit/b72f36c64870df50ff615b4e52783a909940c837 I've added some additional null checks and overall being a little more defensive. This is a speculative fix as I don't have a stack trace or a means to reproduce this.

Changes will be in version `87`. 

Closing now in the hopes this is resolved, if this reproduces in version `87` then please let me know and we can reopen.

**Comment by snowball58** [comment]
Alex,

We’ve upgraded to version 87, and have encountered a similar null reference exception with a similar call stack.


Application shut down due to unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.

   at CefSharp.Internals.ClientAdapter.MethodInvocationComplete(ClientAdapter* , MethodInvocationResult result)

   at CefSharp.Core.ManagedCefBrowserAdapter.MethodInvocationComplete(Object sender, MethodInvocationCompleteArgs e)

   at CefSharp.Internals.ConcurrentMethodRunnerQueue.OnMethodInvocationComplete(MethodInvocationResult e, CancellationToken token) in C:\projects\cefsharp\CefSharp\Internals\ConcurrentMethodRunnerQueue.cs:line 147

   at CefSharp.Internals.ConcurrentMethodRunnerQueue.<>c__DisplayClass7_0.<<Enqueue>b__0>d.MoveNext() in C:\projects\cefsharp\CefSharp\Internals\ConcurrentMethodRunnerQueue.cs:line 43

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Thanks,

Steven

**Comment by amaitland** [comment]
Other than it being a NRE, it's an entirely different stack trace.

https://github.com/cefsharp/CefSharp/blob/cefsharp/87/CefSharp.Core.Runtime/Internals/ClientAdapter.cpp#L1387

Nothing stands out, without a line number to give a hint I'm not sure. Make sure CefSharp.Core.Runtime.pdb is next to the dll.

Can you provide an example that reproduces the problem? If not then source is there, you can build a local copy and attach the debugger yourself.

**Comment by snowball58** [comment]
One our devs encountered the error in a development build (which included all CefSharp pdbs), so we have a more detailed error this time. This occurred during refresh of a CefSharp browser instance. It doesn’t seem to be consistently reproducible, as he was only able to get this to happen once.

Application shut down due to unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Internals.ClientAdapter.MethodInvocationComplete(ClientAdapter* , MethodInvocationResult result) in c:\projects\cefsharp\cefsharp.core.runtime\internals\clientadapter.cpp:line 1395
at CefSharp.Core.ManagedCefBrowserAdapter.MethodInvocationComplete(Object sender, MethodInvocationCompleteArgs e) in c:\projects\cefsharp\cefsharp.core.runtime\managedcefbrowseradapter.cpp:line 210
at CefSharp.Internals.ConcurrentMethodRunnerQueue.OnMethodInvocationComplete(MethodInvocationResult e, CancellationToken token) in C:\projects\cefsharp\CefSharp\Internals\ConcurrentMethodRunnerQueue.cs:line 147
at CefSharp.Internals.ConcurrentMethodRunnerQueue.<>c__DisplayClass7_0.<<Enqueue>b__0>d.MoveNext() in C:\projects\cefsharp\CefSharp\Internals\ConcurrentMethodRunnerQueue.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


***@***.***D71659.0A7F3C10]

Based on that, it looks like either wrapper of wrapper->Browser is null for some reason at this point.


From: Alex Maitland ***@***.***>
Sent: Friday, March 5, 2021 3:25 PM
To: cefsharp/CefSharp ***@***.***>
Cc: Snow, Steven R [AUTOSOL/PSS/AUS] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cefsharp/CefSharp] CefSharp.Internals.ClientAdapter.OnProcessMessageReceived NullReferenceException (#3322)


Other than it being a NRE, it's an entirely different stack trace.

https://github.com/cefsharp/CefSharp/blob/cefsharp/87/CefSharp.Core.Runtime/Internals/ClientAdapter.cpp#L1387 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cefsharp_CefSharp_blob_cefsharp_87_CefSharp.Core.Runtime_Internals_ClientAdapter.cpp-23L1387&d=DwMCaQ&c=jOURTkCZzT8tVB5xPEYIm3YJGoxoTaQsQPzPKJGaWbo&r=0O9ycvvMvkr0eilrFovpjdvhePeZxX0JdBNNzgU_uho&m=CLuq7IrBvYcols91NholWl-dVv4ChoXU3TZ9GzC_j5A&s=bwsO5IjLAlp3Z7EvlztedGnkQGaTLvM_t5negesscjs&e=>

Nothing stands out, without a line number to give a hint I'm not sure. Make sure CefSharp.Core.Runtime.pdb is next to the dll.

Can you provide an example that reproduces the problem? If not then source is there, you can build a local copy and attach the debugger yourself.

**Comment by snowball58** [comment]
To clarify further, the "refresh" action actually involves disposing on the current browser process and reloading the page in another existing browser process that is cached in a set of reserve browsers. We think this is probably a result of the browser disposal.
