### ISSUE TITLE
WPF - WritableBitmapRenderHandler ArgumentOutofRange

### ISSUE THREAD

**Issue by alreves** [cefsharp/CefSharp#3474]
- **What version of the product are you using?** 
package id="CefSharp.Wpf" version="88.2.90" targetFramework="net471"

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    Win10, Win Serv 2016?

- **Are you using `WinForms`, `WPF` or `OffScreen`?** 
WPF

- **What steps will reproduce the problem?**
We are using our internal web application. Cef throws unhandled error on some pages.

- **What is the expected output? What do you see instead?**
![e558986b-4016-49f3-91a8-670407a55ed6](https://user-images.githubusercontent.com/5800838/113709048-b8179900-96ea-11eb-8043-8a3d790494fe.png)

**Comment by amaitland** [comment]
> What steps will reproduce the problem?
We are using our internal web application. Cef throws unhandled error on some pages.

How do you reproduce the problem? What's happening when the exception occurs? I've never seen your application so just saying it occurs isn't helpful. 

> What is the expected output? What do you see instead?

No images of exceptions,  please provide a copy and paste of the exception.  I cannot copy and paste from an image

**Comment by alreves** [comment]
> How do you reproduce the problem? What's happening when the exception occurs? I've never seen your application so just saying it occurs isn't helpful.

   at CefSharp.Wpf.Rendering.WritableBitmapRenderHandler.<>c__DisplayClass4_0.<CreateOrUpdateBitmap>b__0() in C:\projects\cefsharp\CefSharp.Wpf\Rendering\WritableBitmapRenderHandler.cs:line 123

![image](https://user-images.githubusercontent.com/5800838/113827864-6d4e5d80-978c-11eb-9dff-2d3eb9dd5785.png)

Maybe just add try...catch?

> No images of exceptions, please provide a copy and paste of the exception. I cannot copy and paste from an image

System.ArgumentOutOfRangeException: The parameter value must be between '0' and '1604'.
Parameter name: sourceRect
   at System.Windows.Media.Imaging.WriteableBitmap.WritePixelsImpl(Int32Rect sourceRect, IntPtr sourceBuffer, Int32 sourceBufferSize, Int32 sourceBufferStride, Int32 destinationX, Int32 destinationY, Boolean backwardsCompat)
   at CefSharp.Wpf.Rendering.WritableBitmapRenderHandler.<>c__DisplayClass4_0.<CreateOrUpdateBitmap>b__0() in C:\projects\cefsharp\CefSharp.Wpf\Rendering\WritableBitmapRenderHandler.cs:line 123
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by amaitland** [comment]
I need enough information to reproduce the exception. What is happening in your application when the exception occurs?

> Maybe just add try...catch?

You can copy and paste WritableBitmapRenderHandler, add error handling and logging and report back, everything you need to implement your own render handler should be public. 

http://cefsharp.github.io/api/89.0.x/html/P_CefSharp_Wpf_ChromiumWebBrowser_RenderHandler.htm

You can get the current DPI from http://cefsharp.github.io/api/89.0.x/html/P_CefSharp_Wpf_ChromiumWebBrowser_DpiScaleFactor.htm
