### ISSUE TITLE
Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.  at CefSharp.CefSettingsBase..ctor()

### ISSUE THREAD

**Issue by Raghava56** [cefsharp/CefSharp#3734]
Hi
Here are the error details
```
Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found. Stacktrace -->    at CefSharp.CefSettingsBase..ctor()
   at CefSharp.Wpf.CefSettings..ctor()
   at FGTsxsWuDwLGpLuurOShqBCBHHmb.⁮⁮⁬⁬⁫⁯⁭⁫‮⁫⁭⁯‬‎‪‍​⁫⁬‍​‫​⁪‬‏‫⁮‮‏‬⁫‬‍⁭⁫‏‫‍‏‮()
```

I added CefSharp.Wpf package in WPF application. it's working awesome in debug mode, but in .exe getting above error. 
Find few things after searching the error and added to my solution.
1.Added this `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` in the <PropertyGroup> in my project (.csproj file)
2.Checked with 2 ways
       In a first way, I added the below code in App.xaml.cs
 ```
#if ANY CPU
            //Only required for PlatformTarget of AnyCPU
            CefRuntime.SubscribeAnyCpuAssemblyResolver();
         #endif
```

In a second way added a resolver in App.xaml.cs   
```
 private static Assembly Resolver(object sender, ResolveEventArgs args)
    {
        if (args.Name.StartsWith("CefSharp.Core.Runtime"))
        {
            string assemblyName = args.Name.Split(new[] { ',' }, 2)[0] + ".dll";
            string archSpecificPath = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase,
                                                   Environment.Is64BitProcess ? "x64" : "x86",
                                                   assemblyName);

            return File.Exists(archSpecificPath)
                       ? Assembly.LoadFile(archSpecificPath)
                       : null;
        }

        return null;
    }

but still getting the above issue.
Is there anything I missed, can you please help with this.

Thanks in Advance.

**Comment by Raghava56** [comment]
I resolved the issue 
I have two projects in the solution and adding `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` in another project issue is resolved
