### ISSUE TITLE
OffScreen - WaitForRenderIdleAsync possible ObjectDisposedException

### ISSUE THREAD

**Issue by Zubastic** [cefsharp/CefSharp#4597]
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

116.0.190 (116.0.23 - cef binary)

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.NET 7.0

### Implementation

OffScreen

### Reproduction Steps

```c#
using System.Collections.Concurrent;
using System.Net;
using CefSharp;
using CefSharp.OffScreen;
using NLog;

namespace Test;

public class Test
{
    private static async Task Main(string[] args)
    {
        var t2 = Task.Run(async () => await TestAsync());
        await Task.WhenAll(new List<Task> { t2 });
    }

    private static async Task TestAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            Cef.Initialize(new CefSettings { LogSeverity = LogSeverity.Disable }, true, browserProcessHandler: null);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }

        while (true)
        {
            try
            {
                var start = 0L;
                var data = new ConcurrentBag<(string Url, long Id)>();
                const string lnk = "https://google.com/{0}";

                for (var i = start; i < start + 50000; i++)
                {
                    data.Add((string.Format(lnk, i), i));
                }

                var objectsTasks = new Task[Environment.ProcessorCount];
                for (var i = 0; i < Environment.ProcessorCount; i++)
                {
                    var id = i;
                    objectsTasks[i] = Task.Run(() =>
                    {
                        Thread.Sleep(id * 1000);
                        while (data.TryTake(out var d))
                        {
                            if (d.Id > start + 1000)
                            {
                                break;
                            }

                            try
                            {
                                var result = d.Url;
                                AsyncContext.Run(async () =>
                                {
                                    using var browser = new ChromiumWebBrowser(result, requestContext: new RequestContext());
                                    var initialLoadResponse = await browser.WaitForInitialLoadAsync();

                                    if (!initialLoadResponse.Success)
                                    {
                                        if (initialLoadResponse.HttpStatusCode == (int)HttpStatusCode.TooManyRequests)
                                        {
                                            data.Add(d);
                                            return;
                                        }

                                        throw new ArgumentException(string.Format("Page load failed with ErrorCode:{0}, HttpStatusCode:{1}", initialLoadResponse.ErrorCode, initialLoadResponse.HttpStatusCode));
                                    }

                                    await browser.WaitForRenderIdleAsync(cancellationToken: cancellationToken);
                                    var source = await browser.GetSourceAsync();
                                    if (!source.Contains("wrapper", StringComparison.OrdinalIgnoreCase)) // page not loaded correctly
                                    {
                                        data.Add(d);
                                        return;
                                    }

                                    start = d.Id;
                                });
                            }
                            catch (TimeoutException)
                            {
                                data.Add(d);
                            }
                            catch (Exception e)
                            {
                                data.Add(d);
                                Console.WriteLine(e.Message);
                            }

                            Thread.Sleep(500);
                        }

                        return Task.CompletedTask;
                    }, cancellationToken);
                }

                await Task.WhenAll(objectsTasks);
                await Task.Delay(5 * 60 * 1000, cancellationToken);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```

### Expected behavior

Program working file

### Actual behavior

After few hours it came with crash:
```c#
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at CefSharp.OffScreen.DefaultRenderHandler.GetScreenInfo() in C:\projects\cefsharp\CefSharp.OffScreen\DefaultRenderHandler.cs:line 103
   at CefSharp.OffScreen.ChromiumWebBrowser.GetScreenInfo() in C:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 807
   at CefSharp.Internals.RenderClientAdapter.GetScreenInfo(RenderClientAdapter*, scoped_refptr<CefBrowser>* browser, CefScreenInfo* screen_info)
```

```c#
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at CefSharp.OffScreen.ChromiumWebBrowser.<>c__DisplayClass74_0.<WaitForRenderIdleAsync>b__1(Object s, OnPaintEventArgs args) in C:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 731
   at CefSharp.OffScreen.ChromiumWebBrowser.CefSharp.Internals.IRenderWebBrowser.OnPaint(PaintElementType type, Rect dirtyRect, IntPtr buffer, Int32 width, Int32 height) in C:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 897
   at CefSharp.Internals.RenderClientAdapter.OnPaint(RenderClientAdapter*, scoped_refptr<CefBrowser>* browser, cef_paint_element_type_t type, vector<CefRect\,std::allocator<CefRect> >* dirtyRects, Void* buffer, Int32 width, Int32 height)
```

### Does this problem also occur in the CEF Sample Application

Not Tested

**Comment by amaitland** [comment]
- Example is incomplete, it references variables that aren't defined. Example should be self contained, remove anything that's not strictly required to reproduce the issue
- I would expect there to be a single `AsyncContext` per process, Similar to how an application would typically have a single UI thread. `Cef.Initialze` and `Cef.Shutdown` need to be called on the same thread.
- Your example doesn't call `Cef.Shutdown`.
- Use [Parallel.ForEachAsync](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync?view=net-7.0) to simplify your code.
- Use a different website to google.com depending on region/day Google can have animated images that loop indefinitely, the page will never finish rendering. Not ideal as an example.
- Simplify code, remove anything that isn't strictly required to reproduce the problem.

The stack trace suggests an `OnPaint` call happened after the browser has been `Disposed`. Once the example has been simplified it should made this easy enough to debug.

**Comment by amaitland** [comment]
> : added browserProcessHandler set to null, first problem resolved.

`null` is already the default for `browserProcessHandler`

> After fixes with WaitForRenderIdleAsync (I copy this method and add try catch) second problem also resolved.

An exception on timeout is the expected behaviour, it's up to the consumer to handle this correctly.

> Now problem that app crashes after some time without any stack trace.

You should enable logging and check for errors

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#log-file

If there is nothing useful in the log then you can enable crash reporting. 

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

**Comment by Zubastic** [comment]
> An exception on timeout is the expected behaviour, it's up to the consumer to handle this correctly.
Yep, but here problem in handler for timer:
```c#
        //Every time Paint is called we reset our timer
        handler = (s, args) =>
        {
            try
            {
                idleTimer.Stop();
                idleTimer.Start();
            }
            catch (ObjectDisposedException)
            {
                // ignored
            }
            catch (NullReferenceException)
            {
                // ignored
            }
        };
```
Here fixed version. By default NRE and ODE not catched at all, so sometimes it would crash with this exceptions.

> You should enable logging and check for errors
Enabled logs - no any usefull info.

> If there is nothing useful in the log then you can enable crash reporting.
Enabled crash reporting - no any reports but my main proccess crashed with unhandled exception:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-10-18T21:30:03.7064607Z" /> 
  <EventRecordID>1139510</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="280120" ThreadID="34644" /> 
  <Channel>Application</Channel> 
  <Computer>Zubastic-New</Computer> 
  <Security UserID="S-1-5-21-1669309807-670575810-1695442662-1000" /> 
  </System>
<EventData>
  <Data Name="AppName">TicketMonitor.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">64e841c5</Data> 
  <Data Name="ModuleName">KERNELBASE.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.2215</Data> 
  <Data Name="ModuleTimeStamp">83983b0b</Data> 
  <Data Name="ExceptionCode">e0000008</Data> 
  <Data Name="FaultingOffset">000000000006531c</Data> 
  <Data Name="ProcessId">0x19208</Data> 
  <Data Name="ProcessCreationTime">0x1da011ae041a1a3</Data> 
  <Data Name="AppPath">E:\PROJECTS_Git\TicketBot\TicketMonitor\bin\Debug\net7.0\win-x64\TicketMonitor.exe</Data> 
  <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data Name="IntegratorReportId">a118ca92-a306-4a58-9f83-dd0ff562dd3c</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

**Comment by amaitland** [comment]
The `Paint` event is fired on the `CEF UI Thread` by default, so the possibility for the events to be fired nearly concurrently exists. The `WPF` and `OffScreen` implementations have been updated to ignore the `ObjectDisposedException`.

> Enabled crash reporting - no any reports but my main proccess crashed with unhandled exception:

Make sure you run from outside of `Visual Studio` as the `Visual Studio Host Process` can interfere with crash reporting for the browser process.
