### ISSUE TITLE
AggregateException when using EvaluateScriptAsync

### ISSUE THREAD

**Issue by tgeagleeye** [cefsharp/CefSharp#669]
I had just recently changed from master to cef/2171 branch so I could use JSBinding. Now when I try to get a value from a Javascript method using EvaluateScriptAsync, my application fails to continue. No errors are thrown except when I exit the application. To which it throws this:

System.AggregateException occurred
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at MainDisplay.RenderTiles(IEnumerable`1 records, Boolean reDrawTiles) in c:\Projects\VS2012\Test\MainDisplay.cs:line 400
  InnerException: System.ServiceModel.CommunicationException
       HResult=-2146233087
       Message=The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.
       Source=mscorlib
       StackTrace:
         Server stack trace: 
            at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
            at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
            at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
            at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
            at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
         Exception rethrown at [0]: 
            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
            at CefSharp.Internals.IRenderProcess.EndEvaluateScriptAsync(IAsyncResult result)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

I'm not sure what could be causing this, it's not breaking my application thankfully. But I figured you might want this brought to your attention.

**Comment by nickstinger** [comment]
I get an AggregateException when the script returns a non-trivial value.  If in doubt, try returning true.

**Comment by amaitland** [comment]
@nickstinger version `39` will have better support for returning complex objects, it'll return a `Dictionary<string, object>`, the same as `CefSharp1` did.

If you feel like taking it for a spin you can try building https://github.com/cefsharp/CefSharp/tree/cef/2171 from source (CI `nuget` packages builds are currently broken)

**Comment by nickstinger** [comment]
I already have.  I was looking for a nice way to grab full-page screenshots from an interactive browser.  I solved the problem, but without modifying any code.  I just needed a little understanding (via the Rendering event and a ViewBox).  I'm most looking forward to the future return of WPF printing.  Thanks for all your efforts!
