### ISSUE TITLE
Random error when executing js

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#747]
Hi Guys
I encounter this random error lately. It is when I execute js call from cefsharp WPF. Unfortunately the error message is not helpful. Below is the stacktrace:
```
System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException: The client was unable to process the callback request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from CallbackBehaviorAttribute or from the <clientDebug> configuration behavior) on the client in order to send the exception information back to the server, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the client trace logs.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.EndEvaluateScriptAsync(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Mailbird.Shared.Controls.WebControl.EvaluateScript(String script) in c:\Users\Dimas\Documents\Projects\WindowsMail\Mailbird.Shared\Controls\WebControl.cs:line 499
---> (Inner Exception #0) System.ServiceModel.FaultException: The client was unable to process the callback request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from CallbackBehaviorAttribute or from the <clientDebug> configuration behavior) on the client in order to send the exception information back to the server, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the client trace logs.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeEndService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.EndEvaluateScriptAsync(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)```

Do you guys know what causes that?

**Comment by amaitland** [comment]
Can you create a reproducible sample? Preferably modify the WPF example project.

When you create an issue can you include more information please. Need to know what version your using, environment, steps to reproduce, etc

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by myrnazhou** [comment]
I'm running it in Windows 8.1 64 bit. The version that I was running is from here https://github.com/Bodekaer/CefSharp/commits/feature/2171-drag-drop. 

It's pretty hard to reproduce it. I was just wondering whether it's a known error, so maybe I can find it myself what's wrong in my code.

**Comment by amaitland** [comment]
Are you returning an object? I've seen a similar problem when returning an object too complex for `CefSharp` to map.

Try debugging https://github.com/Bodekaer/CefSharp/blob/feature/2171-drag-drop/CefSharp.BrowserSubprocess.Core/CefBrowserWrapper.h#L50

The branch your using is a bit out of date, would be helpful if it was up to date with `cef/2171`.

> System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException: The client was unable to process the callback request due to an internal error. For more information about the error, either turn on IncludeExceptionDetailInFaults (either from CallbackBehaviorAttribute or from the <clientDebug> configuration behavior) on the client in order to send the exception information back to the server, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the client trace logs.

Try merging https://github.com/cefsharp/CefSharp/commit/9f7729c037e2af5fce75f6b4f5c6639560bebbdd into your branch

The client trace log sounds like it could be useful http://msdn.microsoft.com/en-us/library/ms731859.aspx

**Comment by amaitland** [comment]
@myrnazhou Did `IncludeExceptionDetailInFaults` provide any additional information?

**Comment by myrnazhou** [comment]
After I did the last pull from 2171, the error seems gone. As I remember, when the error happened the performance was also very slow. So it might be related, but not sure. 

Should I close this issue for now?

**Comment by amaitland** [comment]
Close for now and reopen if it's still a problem?

**Comment by myrnazhou** [comment]
Ok I just got the error again. So yes, it happened when it was really slow. The initialization itself took more than 5s.

```System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.ServiceModel.Channels.ServiceChannel'.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.Begin()
   at System.ServiceModel.Channels.ServiceChannel.BeginCall(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, TimeSpan timeout, AsyncCallback callback, Object asyncState)
   at System.ServiceModel.Channels.ServiceChannel.BeginCall(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, AsyncCallback callback, Object asyncState)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeBeginService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.BeginEvaluateScriptAsync(Int32 browserId, Int64 frameId, String script, Nullable`1 timeout, AsyncCallback callback, Object state)
   at CefSharp.Internals.BrowserProcessServiceHost.<>c__DisplayClass5.<EvaluateScriptAsync>b__4(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Mailbird.Shared.Controls.WebControl.EvaluateScript(String script) in c:\Users\Dimas\Documents\Projects\WindowsMail\Mailbird.Shared\Controls\WebControl.cs:line 499
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.ServiceModel.Channels.ServiceChannel'.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.Begin()
   at System.ServiceModel.Channels.ServiceChannel.BeginCall(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, TimeSpan timeout, AsyncCallback callback, Object asyncState)
   at System.ServiceModel.Channels.ServiceChannel.BeginCall(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, AsyncCallback callback, Object asyncState)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeBeginService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at CefSharp.Internals.IRenderProcess.BeginEvaluateScriptAsync(Int32 browserId, Int64 frameId, String script, Nullable`1 timeout, AsyncCallback callback, Object state)
   at CefSharp.Internals.BrowserProcessServiceHost.<>c__DisplayClass5.<EvaluateScriptAsync>b__4(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by amaitland** [comment]
Is it reliably reproducible? Can you produce a sample?

**Comment by myrnazhou** [comment]
No, even in my development environment it's quite hard to replicate it. But I saw that it gave more info about the error now, ```System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.ServiceModel.Channels.ServiceChannel'.```, maybe you know about it?

**Comment by amaitland** [comment]
Without a way to reproduce I'm not sure there is much I can do, sorry.

**Comment by amaitland** [comment]
@myrnazhou Any further comment on this?

**Comment by amaitland** [comment]
Did you resolve this before mailbird was shipped?

**Comment by myrnazhou** [comment]
I can't really replicate this, so I'm going to close it for now.
