### ISSUE TITLE
NullReferenceException  Crash on CefSharp.Wpf 37.0.0 (stable)

### ISSUE THREAD

**Issue by kropewnicki** [cefsharp/CefSharp#804]
I am getting a strange crash on cefsharp:

Here is the call stack:
```c#
[code/stracktraces]
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=CefSharp.Core
  StackTrace:
       at CefSharp.Internals.ClientAdapter.GetCefBrowser(ClientAdapter* , CefRefPtr<CefBrowser>* )
       at CefSharp.Internals.RenderClientAdapter.TryGetCefMainFrame(RenderClientAdapter* , CefRefPtr<CefFrame>* )
       at CefSharp.ManagedCefBrowserAdapter.LoadUrl(String address)
       at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)
       at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
  InnerException:
```
[code/stracktraces]

I was also getting the crash on CefSharp.Wpf 37.0.0-pre02
but the call stack was different

```c#
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The communication object, CefSharp.Internals.BrowserProcessServiceHost, cannot be modified while it is in the Closing state.
  Source=System.ServiceModel
  StackTrace:
       at System.ServiceModel.Channels.CommunicationObject.ThrowIfClosedOrOpened()
       at System.ServiceModel.ServiceHostBase.OnAddChannelDispatcher(ChannelDispatcherBase channelDispatcher)
       at System.ServiceModel.Dispatcher.ChannelDispatcherCollection.InsertItem(Int32 index, ChannelDispatcherBase item)
       at System.Collections.Generic.SynchronizedCollection`1.Add(T item)
       at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
       at System.ServiceModel.ServiceHostBase.InitializeRuntime()
       at System.ServiceModel.ServiceHostBase.OnBeginOpen()
       at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Open()
       at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)
       at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
  InnerException: 
```

**Comment by kropewnicki** [comment]
Do you have any suggestions on how to gracefully handle or recover from this crash?

**Comment by kropewnicki** [comment]
I tried on CefSharp.Wpf 39.0.0-pre02

and I get the same crash.

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The communication object, CefSharp.Internals.BrowserProcessServiceHost, cannot be modified while it is in the Closing state.
  Source=System.ServiceModel
  StackTrace:
       at System.ServiceModel.Channels.CommunicationObject.ThrowIfClosedOrOpened()
       at System.ServiceModel.ServiceHostBase.OnAddChannelDispatcher(ChannelDispatcherBase channelDispatcher)
       at System.ServiceModel.Dispatcher.ChannelDispatcherCollection.InsertItem(Int32 index, ChannelDispatcherBase item)
       at System.Collections.Generic.SynchronizedCollection`1.Add(T item)
       at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
       at System.ServiceModel.ServiceHostBase.InitializeRuntime()
       at System.ServiceModel.ServiceHostBase.OnBeginOpen()
       at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Open()
       at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)
       at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
  InnerException:

**Comment by jornh** [comment]
> Do you have any suggestions on how to gracefully handle or recover from this crash?

For implementing your very own "he's dead Jim" handling see https://github.com/cefsharp/CefSharp/issues/788#issuecomment-72950103 ...  (and maybe a few posts onwards ... )

under what circumstances do you see the crash (e.g use of Javascript binding etc etc?)? Reproducible on a public page somewhere?

**Comment by kropewnicki** [comment]
right now i am checking the latest master branch.   to see if i can trace it there.

**Comment by amaitland** [comment]
Side note, please markup any `code/stracktraces`, they're awfully hard to read otherwise :+1: 

If the bug is reproducible then if you can fork the relevant example and push to `GitHub` that would make it a lot easier for someone to look into it further.

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by kropewnicki** [comment]
Sorry for the delay, but I figured out the cause.   My application is rapidly toggling between different web pages,   Somewhere is race condition.  

But anyway I am able to work around this by just catching the exception, when I try to load the URL.

I will see if it I can make a demo application that breaks in this way, but it is not as critical as before.

**Comment by amaitland** [comment]
Added an extra check before calling `Open` on the `WCF` host

Hope this helps https://github.com/cefsharp/CefSharp/commit/387101ee79b730d593d701b88e5fc521381fd964

**Comment by amaitland** [comment]
@kropewnicki Is this a reproducible issue? Were/are you able to test again using `master` or a `CI` build?

**Comment by kropewnicki** [comment]
I could not narrow down the cause to reproduce it.

I suspect it was due to a timing issue as I rapidly loaded new web pages.

**Comment by amaitland** [comment]
Sounds like you found a way around this, if someone has a way to reliably reproduce the problem then feel free to comment and we'll reopen this.
