### ISSUE TITLE
WinForms ParentFormMessageInterceptor Arithmetic Overflow x64

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#918]
So the `ToInt32()` calls are throwing an exception when running under `x64`, no real surprise, just a standard overflow. Just need to deal with the `x64` variation.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/Internals/ParentFormMessageInterceptor.cs#L152

```
System.OverflowException was unhandled by user code
  HResult=-2146233066
  Message=Arithmetic operation resulted in an overflow.
  Source=mscorlib
  StackTrace:
       at System.IntPtr.ToInt32()
       at CefSharp.WinForms.Internals.ParentFormMessageInterceptor.WndProc(Message& m) in c:\projects\github\CefSharp\CefSharp.WinForms\Internals\ParentFormMessageInterceptor.cs:line 152
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
       at System.Windows.Forms.Form.DefWndProc(Message& m)
       at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WmWindowPosChanged(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException: 
```

Easy enough to reproduce
- Open the `WinForms Example` using `x64` build
- `Minimize` the window.

**Comment by amaitland** [comment]
Simple enough solution is to use something like http://referencesource.microsoft.com/#WindowsBase/Shared/MS/Win32/NativeMethodsOther.cs,432

Probably create an extension method in the `CefSharp` library, as there is a place in the `WPF` code that would also benefit from such a method.

**Comment by amaitland** [comment]
@rassilon Any comment on this one?

**Comment by rassilon** [comment]
Yeah, check out the PR I just pushed.
