### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by rstmm** [cefsharp/CefSharp#976]
Hi,

we are experiencing the following problem:

We're tracking sensor data in an hybrid js-app, which runs in Chromium Wrapper in C#.
After running the experiments for 2 days, our App crashes and we find this error in event log:

```
Application: CefSharp.BrowserSubprocess.exe
Frameworkversion: v4.0.30319
Description: Process has been stopped due to an exception.
Exception informationen: System.AccessViolationException
Stack:
   at <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
   at CefSharp.CefAppWrapper.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```

What could this cause to happen?

I thought about too much RAM usage, but when I try to produce the same data in a shorter amount of time, The app crashes, but with the following error in libdef.dll in event log (unfortunately, not much information provided). RAM usage was at that time above 1 GB, but there were about 2 GB left on the system.

```
Name of defective application: CefSharp.BrowserSubprocess.exe, Version: 39.0.0.0, timestamp: 0x5534e6b5
Name of defective module: libcef.dll, Version: 3.2171.2069.0, timestamp: 0x5511ef73
Exception code: 0x4000001f
Error offset: 0x00be3043
ID of defective process: 0x4fd0
Time of defective application: 0x01d080bc598208b0
Path of defective application: xxx\bin\x86\Debug\CefSharp.BrowserSubprocess.exe
Path of defective module: xxx\bin\x86\Debug\libcef.dll
Report Id: 231cf990-ecb1-11e4-bff1-dda77a2114af
```

**Comment by amaitland** [comment]
Can you translate that to English?

**Comment by rstmm** [comment]
Sorry, please see updated question

**Comment by amaitland** [comment]
Thanks :smile:

**Comment by rstmm** [comment]
I'm not sure anymore if this exception is due to our long running data gathering:

I just did some small tests, closed the application, an while the application was closing, I received another AccessViolationException, with a different call stack:

   at CefSharp.Internals.ClientAdapter.CloseAllPopups(ClientAdapter* , Boolean forceClose)
   at CefSharp.ManagedCefBrowserAdapter.CloseAllPopups(Boolean forceClose)
   at CefSharp.ManagedCefBrowserAdapter.DoDispose(Boolean isDisposing)
   at CefSharp.DisposableResource.Dispose()
   at CefSharp.ManagedCefBrowserAdapter.Dispose(Boolean A_0)
   at CefSharp.ManagedCefBrowserAdapter.Dispose()
   at CefSharp.Wpf.ChromiumWebBrowser.Dispose(Boolean isdisposing)
   at CefSharp.Wpf.ChromiumWebBrowser.Dispose()
   at CefSharp.Cef.Shutdown()
   at CefSharp.Wpf.ChromiumWebBrowser.OnApplicationExit(Object sender, ExitEventArgs e)
   at System.Windows.ExitEventHandler.Invoke(Object sender, ExitEventArgs e)
   at System.Windows.Application.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at xxx.App.Main() in xxx\obj\x86\Debug\App.g.cs:Zeile 0.
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by amaitland** [comment]
One is in the `Render Process` and another is in your main app, so possibly two different exceptions. 

Are you using popups? Do you call `Cef.Initialize()` explicitly? If so on what thread?

**Comment by rstmm** [comment]
No we don't use popups, and yes we call Cef.Initialize() explicitly from the UI thread at start time of the application.

**Comment by amaitland** [comment]
For the first exception a set of debug symbols is likely required to find out some more information, will have to get back to you on that one as they're not readily available due to some technical difficulties.

**Comment by amaitland** [comment]
`Symbols` are available here https://github.com/cefsharp/cef-binary/releases/tag/v3.2171.2069

**Comment by amaitland** [comment]
@rstmm Are you able to reproduce the problem with the latest version? There's also a `-pre` release out based on `Chromium 43` which is a major rewrite of `CefSharp`, so you'll have much more control, a lot of object `dispose` cleanup was also done, so worth taking it for a spin.

**Comment by rstmm** [comment]
I'm not working on that project anymore, I'm sorry I can't verify that...

**Comment by amaitland** [comment]
Ok no problem. If you do come back to this then feel free to reopen if necessary.

**Comment by robinwassen** [comment]
Just want to mention that we bumped in to the exception mentioned in the first post using CefSharp 43, and we do not use popups.

Still don't know the cause though.

**Comment by amaitland** [comment]
> Just want to mention that we bumped in to the exception mentioned in the first post using CefSharp 43, and we do not use popups.

Have you upgraded to `43.0.1`? If you can reproduce the problem then feel free to create a new issue.

**Comment by robinwassen** [comment]
We found the cause after a lot of investigating.

The cef_200_percent.pak was missing in our builds and it caused this exception to be thrown if the application was running on a PC with ~200% DPI scaling (at least in Win 10). Kind of hard one to find since all our dev machines run 100% DPI scaling.

I think this exception will be thrown on ~100% DPI scaling machines if cef_100_percent.pak is missing, but have not confirmed that.

So it was no problem in CefSharp after all.

**Comment by amaitland** [comment]
> The cef_200_percent.pak was missing in our builds and it caused this exception to be thrown if the application was running on a PC with ~200% DPI scaling (at least in Win 10). Kind of hard one to find since all our dev machines run 100% DPI scaling.

Very interesting! Thanks for taking the time to report back :+1:

**Comment by lsim** [comment]
In the hope that this may save others some pain: 

I saw this same error and stack trace when I accidentally ran my app with an incorrect working directory
